### ISSUE TITLE
List of redirects

### ISSUE THREAD

**Issue by Meiryo7743** [Meiryo7743/COVID-19-Ichikawa#74]
リダイレクト項目数が多くなり把握するのが大変になってきたため，ディレクトリ名の変更に伴うリダイレクトの一覧をここにまとめることにする。

ここに記載されているリンクは netlify.toml にて正しい URL に誘導するよう設定しなければならない。

**Comment by Meiryo7743** [comment]
# /contacts

```toml
[[redirects]]
  from = "/contacts"
  to = "https://forms.gle/rJAhPqckU1Ak7tFQ9"
  force = true

 [[redirects]]
  from = "/en/contacts"
  to = "https://forms.gle/rJAhPqckU1Ak7tFQ9"
  force = true
```
